.js   17:1   error  This line has a length of 81. Maximum allowed is 80  max-len   23:1   error  Expected indentation of 2 spaces but found 8         indent   24:1   error  Expected indentation of 2 spaces but found 8         indent   25:1   error  Expected indentation of 4 spaces but found 10        indent   26:1   error  Expected indentation of 8 spaces but found 12        indent   27:1   error  Expected indentation of 8 spaces but found 12        indent   28:1   error  Expected indentation of 4 spaces but found 10        indent   29:1   error  Expected indentation of 2 spaces but found 8         indent   30:1   error  Expected indentation of 2 spaces but found 8         indent   31:1   error  Expected indentation of 2 spaces but found 8         indent   32:1   error  This line has a length of 81. Maximum allowed is 80  max-len   32:1   error  Expected indentation of 2 spaces but found 8         indent   34:1   error  Expected indentation of 2 spaces but found 8         indent   36:1   error  Expected indentation of 2 spaces but found 8         indent   37:1   error  Expected indentation of 4 spaces but found 10        indent   38:1   error  Expected indentation of 4 spaces but found 10        indent   39:1   error  Expected indentation of 4 spaces but found 10        indent   40:1   error  Expected indentation of 4 spaces but found 10        indent   41:1   error  Expected indentation of 4 spaces but found 10        indent   42:1   error  Expected indentation of 6 spaces but found 12        indent   43:1   error  Expected indentation of 4 spaces but found 10        indent   44:1   error  Expected indentation of 6 spaces but found 12        indent   45:1   error  Expected indentation of 8 spaces but found 14        indent   46:1   error  Expected indentation of 6 spaces but found 12        indent   47:1   error  Expected indentation of 4 spaces but found 10        indent   49:1   error  Expected indentation of 4 spaces but found 10        indent   50:1   error  Expected indentation of 4 spaces but found 10        indent   51:1   error  Expected indentation of 6 spaces but found 12        indent   52:1   error  Expected indentation of 6 spaces but found 12        indent   53:1   error  Expected indentation of 6 spaces but found 12        indent   54:1   error  Expected indentation of 6 spaces but found 12        indent   55:1   error  Expected indentation of 4 spaces but found 10        indent   57:1   error  Expected indentation of 4 spaces but found 10        indent   58:1   error  Expected indentation of 4 spaces but found 10        indent   59:1   error  Expected indentation of 4 spaces but found 10        indent   61:1   error  Expected indentation of 4 spaces but found 10        indent   62:1   error  This line has a length of 86. Maximum allowed is 80  max-len   62:1   error  Expected indentation of 8 spaces but found 12        indent   62:87  error  Missing trailing comma                               comma-dangle   63:1   error  Expected indentation of 4 spaces but found 10        indent   65:1   error  This line has a length of 82. Maximum allowed is 80  max-len   65:1   error  Expected indentation of 4 spaces but found 10        indent   66:1   error  Expected indentation of 4 spaces but found 10        indent   67:1   error  Expected indentation of 4 spaces but found 10        indent   68:1   error  Expected indentation of 6 spaces but found 12        indent   69:1   error  Expected indentation of 10 spaces but found 14       indent   70:74  error  Missing trailing comma                               comma-dangle   71:1   error  Expected indentation of 6 spaces but found 12        indent   72:1   error  Expected indentation of 4 spaces but found 10        indent   74:1   error  Expected indentation of 4 spaces but found 10        indent   75:1   error  Expected indentation of 2 spaces but found 8         indent   76:1   error  Expected indentation of 4 spaces but found 10        indent   77:1   error  Expected indentation of 4 spaces but found 10        indent   78:1   error  Expected indentation of 6 spaces but found 12        indent   79:1   error  Expected indentation of 4 spaces but found 10        indent   80:1   error  Expected indentation of 4 spaces but found 10        indent   81:1   error  Expected indentation of 8 spaces but found 12        indent   82:1   error  Expected indentation of 8 spaces but found 12        indent   83:1   error  Expected indentation of 8 spaces but found 12        indent   84:1   error  Expected indentation of 4 spaces but found 10        indent   85:1   error  Expected indentation of 2 spaces but found 8         indent
✖ 61 problems (61 errors, 0 warnings)
  57 errors and 0 warnings potentially fixable with the `--fix` option.

Error: functions predeploy error: Command terminated with non-zero exit code 1